"use client";
import {useEffect,useMemo,useState} from "react";
import {LayoutDashboard,Boxes,ShoppingBag,Store,CreditCard,WalletCards,Settings,Plus,Download,Search,Truck,X,Menu} from "lucide-react";
import * as XLSX from "xlsx";

type Status="입고전"|"입고완료"|"촬영대기"|"판매중"|"예약"|"판매완료";
type Product={id:string;batch:string;date:string;brand:string;category:string;name:string;size?:string;color?:string;status:Status;purchaseType:string;cost:number;totalCost:number;ems?:string;bundle?:string;auction?:string;platforms:string[]};
type Sale={id:string;productId:string;channel:string;gross:number;fee:number;shipping:number;net:number;date:string};
type View="dashboard"|"inventory"|"purchases"|"platforms"|"sales"|"cash"|"settings";

const seed:Product[]=[
{id:"SME-2608-0001",batch:"JP-AUC-2608-01",date:"2026-08-17",brand:"RED VALENTINO",category:"원피스",name:"비주 플라워 블랙 롱 원피스",size:"38 / M 상당",color:"블랙",status:"입고전",purchaseType:"일본경매직구",cost:200073,totalCost:200073,ems:"EN534239425JP",bundle:"38134",auction:"l1237483222",platforms:[]},
{id:"SME-2608-0002",batch:"JP-AUC-2608-02",date:"2026-08-15",brand:"WEEKEND Max Mara",category:"원피스",name:"실크 100% 체크 카라 원피스",size:"40",color:"네이비 체크",status:"입고전",purchaseType:"일본경매직구",cost:56109,totalCost:56109,ems:"EN534751648JP",bundle:"38133",auction:"q1239976985",platforms:[]},
{id:"SME-2608-0003",batch:"JP-AUC-2608-02",date:"2026-08-15",brand:"RED VALENTINO",category:"셋업",name:"보더 리본 탑 + 쇼트팬츠 셋업",size:"XS/S",color:"블랙/화이트",status:"입고전",purchaseType:"일본경매직구",cost:80835,totalCost:80835,ems:"EN534751648JP",bundle:"38133",auction:"s1237006571",platforms:[]},
{id:"SME-2608-0004",batch:"JP-AUC-2608-02",date:"2026-08-15",brand:"ISABEL MARANT ETOILE",category:"원피스",name:"스카프 패션 원피스",color:"화이트 계열",status:"입고전",purchaseType:"일본경매직구",cost:102185,totalCost:102185,ems:"EN534751648JP",bundle:"38133",auction:"l1229309438",platforms:[]},
{id:"SME-2608-0005",batch:"JP-AUC-2608-02",date:"2026-08-15",brand:"CEDRIC CHARLIER",category:"니트",name:"울 사이드 슬릿 그라데이션 니트",color:"그레이 계열",status:"입고전",purchaseType:"일본경매직구",cost:46137,totalCost:46137,ems:"EN534751648JP",bundle:"38133",auction:"c1238025019",platforms:[]},
{id:"SME-2608-0006",batch:"JP-AUC-2608-02",date:"2026-08-15",brand:"ENFOLD",category:"탑",name:"애시메트리 노슬리브 컷소",color:"화이트 계열",status:"입고전",purchaseType:"일본경매직구",cost:46137,totalCost:46137,ems:"EN534751648JP",bundle:"38133",auction:"g1239629164",platforms:[]},
{id:"SME-2608-0007",batch:"JP-AUC-2608-02",date:"2026-08-15",brand:"ENFOLD",category:"원피스",name:"V넥 더블 오버 원피스",color:"그레이/카키 계열",status:"입고전",purchaseType:"일본경매직구",cost:108250,totalCost:108250,ems:"EN534751648JP",bundle:"38133",auction:"g1239623889",platforms:[]},
{id:"SME-2608-0008",batch:"JP-AUC-2608-03",date:"2026-08-14",brand:"Max Mara",category:"셋업",name:"실크 셋업 롱 원피스",color:"플로럴/멀티",status:"입고전",purchaseType:"일본경매직구",cost:114000,totalCost:114000,ems:"EN534454741JP",bundle:"38130",auction:"l1236394741",platforms:[]},
{id:"SME-2608-0009",batch:"JP-AUC-2608-03",date:"2026-08-14",brand:"self-portrait",category:"자켓",name:"트위드 노카라 자켓",size:"8",color:"네이비",status:"입고전",purchaseType:"일본경매직구",cost:156143,totalCost:156143,ems:"EN534454741JP",bundle:"38130",auction:"m1221101694",platforms:[]}
];
const batches=[
{id:"JP-AUC-2608-01",bundle:"38134",ems:"EN534239425JP",count:1,cost:200073},
{id:"JP-AUC-2608-02",bundle:"38133",ems:"EN534751648JP",count:6,cost:439653},
{id:"JP-AUC-2608-03",bundle:"38130",ems:"EN534454741JP",count:2,cost:270143}
];
const nav=[["dashboard","대시보드",LayoutDashboard],["inventory","상품·재고",Boxes],["purchases","매입·수입",ShoppingBag],["platforms","플랫폼 등록",Store],["sales","판매·정산",CreditCard],["cash","금전·비용",WalletCards],["settings","설정",Settings]] as const;
const won=(n:number)=>new Intl.NumberFormat("ko-KR",{style:"currency",currency:"KRW",maximumFractionDigits:0}).format(n);

export default function Page(){
 const [view,setView]=useState<View>("dashboard"),[products,setProducts]=useState(seed),[sales,setSales]=useState<Sale[]>([]),[q,setQ]=useState(""),[modal,setModal]=useState<"product"|"sale"|null>(null),[mobile,setMobile]=useState(false);
 useEffect(()=>{const r=localStorage.getItem("sm-everflow-v01b");if(r)try{const x=JSON.parse(r);if(x.products)setProducts(x.products);if(x.sales)setSales(x.sales)}catch{}},[]);
 useEffect(()=>{localStorage.setItem("sm-everflow-v01b",JSON.stringify({products,sales}))},[products,sales]);
 const inv=products.filter(p=>p.status!=="판매완료"), total=inv.reduce((a,b)=>a+b.totalCost,0), gross=sales.reduce((a,b)=>a+b.gross,0), net=sales.reduce((a,b)=>a+b.net,0);
 const filtered=useMemo(()=>products.filter(p=>(p.id+" "+p.brand+" "+p.name).toLowerCase().includes(q.toLowerCase())),[products,q]);
 function excel(){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([["SM EVERFLOW | WEB EXPORT"],["현재 재고",inv.length],["재고 관리완전원가",total],["누적 판매총액",gross],["실제 정산액",net]]),"01_대시보드");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(products.map(p=>({상품ID:p.id,배치ID:p.batch,매입일:p.date,매입유형:p.purchaseType,브랜드:p.brand,품목:p.category,상세명:p.name,사이즈:p.size||"",컬러:p.color||"",재고상태:p.status,현재확인원가:p.cost,경영관리완전원가:p.totalCost,EMS:p.ems||"",묶음번호:p.bundle||"",경매번호:p.auction||""}))),"02_상품마스터");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(batches.map(b=>({배치ID:b.id,묶음번호:b.bundle,EMS:b.ems,상품수:b.count,현재확인원가:b.cost,상태:"국제배송중"}))),"03_배치마스터");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(sales),"08_매출정산");XLSX.writeFile(wb,"SM_EVERFLOW_WEB_EXPORT.xlsx")}
 function addProduct(fd:FormData){const cost=Number(fd.get("cost")||0);const p:Product={id:`SME-2608-${String(products.length+1).padStart(4,"0")}`,batch:String(fd.get("batch")||`FIELD-2608-${products.length+1}`),date:new Date().toISOString().slice(0,10),brand:String(fd.get("brand")||""),category:String(fd.get("category")||"기타"),name:String(fd.get("name")||""),status:"입고완료",purchaseType:String(fd.get("purchaseType")||"국내현금매입"),cost,totalCost:cost,platforms:[]};setProducts([p,...products]);setModal(null)}
 function addSale(fd:FormData){const productId=String(fd.get("productId")),g=Number(fd.get("gross")||0),fee=Number(fd.get("fee")||0),ship=Number(fd.get("shipping")||0);setSales([{id:`SALE-${Date.now()}`,productId,channel:String(fd.get("channel")||""),gross:g,fee,shipping:ship,net:g-fee-ship,date:new Date().toISOString().slice(0,10)},...sales]);setProducts(products.map(p=>p.id===productId?{...p,status:"판매완료"}:p));setModal(null)}
 return <div className="shell">
  <aside className={mobile?"open":""}><div className="brand"><div className="mark">SM</div><div><b>EVERFLOW</b><span>PRIVATE OPERATIONS</span></div><button onClick={()=>setMobile(false)}><X size={18}/></button></div><nav>{nav.map(([id,label,Icon])=><button className={view===id?"active":""} key={id} onClick={()=>{setView(id);setMobile(false)}}><Icon size={17}/><span>{label}</span>{id==="inventory"&&<em>{inv.length}</em>}</button>)}</nav><div className="mode"><i/><div><b>DEMO MODE</b><span>브라우저 로컬 저장</span></div></div></aside>
  {mobile&&<div className="shade" onClick={()=>setMobile(false)}/>}
  <main><header><div className="title"><button onClick={()=>setMobile(true)}><Menu size={20}/></button><div><small>SM EVERFLOW / OPERATIONS</small><h1>{nav.find(n=>n[0]===view)?.[1]}</h1></div></div><div className="actions"><button className="btn light" onClick={excel}><Download size={16}/>Excel</button><button className="btn dark" onClick={()=>setModal("product")}><Plus size={16}/>빠른 매입</button></div></header>
  <div className="content">
   {view==="dashboard"&&<><Intro title="오늘의 운영 현황" copy="재고 수량보다 상품별 상태와 원가 완성도를 먼저 봅니다."/><div className="kpis"><Kpi dark label="현재 재고" value={`${inv.length}점`} note={`${inv.filter(p=>p.status==="입고전").length}점 국제배송중`}/><Kpi label="현재 확인 원가" value={won(total)} note="1차결제·통관비 미반영 가능"/><Kpi label="관리 완전원가" value={won(total)} note="공통비 배부 전 현재값"/><Kpi label="활성 판매등록" value="0건" note="판매 시 타 플랫폼 확인"/><Kpi label="누적 판매" value={won(gross)} note={`실제정산 ${won(net)}`}/><Kpi label="미정산" value={won(0)} note="플랫폼별 정산 추적"/></div><div className="grid"><section className="panel"><Head over="INBOUND" title="일본 → 한국 입고 예정"/>{batches.map(b=><div className="ship" key={b.id}><div className="shipIcon"><Truck size={18}/></div><div><b>{b.id}</b><span className="pill">국제배송중</span><small>묶음 {b.bundle} · EMS {b.ems}</small></div><div className="shipValue"><b>{b.count}점</b><span>{won(b.cost)}</span></div></div>)}</section><section className="panel"><Head over="COST COMPLETENESS" title="원가 완성도"/><Progress label="2차결제 확인" n="9/9" pct={100}/><Progress label="1차결제 입력" n="0/9" pct={0}/><Progress label="통관비 확정" n="0/9" pct={0}/><div className="notice"><b>아직 총 매입원가가 아닙니다.</b><span>현재 909,869원은 캡처로 확인된 비용입니다. 1차결제와 한국 통관비를 추가해야 완전원가가 됩니다.</span></div></section></div><section className="panel tablePanel"><Head over="RECENT INVENTORY" title="최근 상품"/><Table rows={products.slice(0,6)}/></section></>}
   {view==="inventory"&&<><Intro title="상품 하나를 끝까지 추적합니다." copy="실물 한 점마다 상품ID 하나. 매입·게시·판매·정산이 이 ID에 붙습니다."/><div className="toolbar"><div><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="상품ID, 브랜드, 상품명 검색"/></div><span>{filtered.length}개 상품</span></div><section className="panel tablePanel"><Table rows={filtered}/></section></>}
   {view==="purchases"&&<><Intro title="상품과 배치를 동시에 봅니다." copy="EMS 한 묶음, 일본 출장 한 번, 국내 현금매입 묶음을 각각 비용 단위로 관리합니다."/><div className="batchGrid">{batches.map(b=><section className="panel" key={b.id}><div className="batchTop"><div><small>{b.id}</small><h3>메루카리 직구 / Yahoo!옥션</h3></div><span className="pill">국제배송중</span></div><div className="route"><span>일본 창고</span><i/><Truck size={17}/><i/><span>한국 입고</span></div><div className="stats"><div><span>묶음</span><b>{b.bundle}</b></div><div><span>EMS</span><b>{b.ems}</b></div><div><span>상품</span><b>{b.count}점</b></div><div><span>확인원가</span><b>{won(b.cost)}</b></div></div><div className="warn">1차결제 · 통관비 입력 필요</div></section>)}</div></>}
   {view==="platforms"&&<><Intro title="상품 1개, 게시물은 여러 개." copy="스마트스토어·당근·번개·중고나라에 올라간 게시물을 상품ID로 연결합니다."/><div className="platforms">{["스마트스토어","당근마켓","번개장터","중고나라","오프라인도매"].map(x=><section className="panel" key={x}><span>{x}</span><b>0</b><small>판매중</small></section>)}</div><Empty title="아직 등록된 판매 게시물이 없습니다." copy="입고 후 게시물을 추가하면 상품ID 기준으로 관리합니다."/></>}
   {view==="sales"&&<><Intro title="판매가와 실제 입금액은 분리합니다." copy="플랫폼 수수료와 배송비를 빼고 실제 정산액까지 추적합니다." action={<button className="btn dark" onClick={()=>setModal("sale")}><Plus size={16}/>판매 입력</button>}/>{sales.length===0?<Empty title="아직 판매 데이터가 없습니다." copy="첫 판매부터 입력하면 원가 대비 실제 마진을 추적합니다."/>:<section className="panel tablePanel"><div className="tableWrap"><table><thead><tr><th>상품ID</th><th>채널</th><th>판매가</th><th>수수료</th><th>배송비</th><th>실제정산</th></tr></thead><tbody>{sales.map(s=><tr key={s.id}><td>{s.productId}</td><td>{s.channel}</td><td>{won(s.gross)}</td><td>{won(s.fee)}</td><td>{won(s.shipping)}</td><td><b>{won(s.net)}</b></td></tr>)}</tbody></table></div></section>}</>}
   {view==="cash"&&<><Intro title="실제 돈의 흐름을 놓치지 않습니다." copy="실제 출금·입금과 세무상 처리는 분리해서 기록합니다."/><div className="kpis three"><Kpi dark label="확인 매입지출" value={won(total)} note="현재 확인된 비용"/><Kpi label="판매 정산입금" value={won(net)} note="실제 정산액 누계"/><Kpi label="공통비용" value={won(0)} note="출장·숙박·교통·기타"/></div><Empty title="금전출납은 다음 입력부터 쌓입니다." copy="일본 출장비와 국내 현금매입, 플랫폼 정산을 실제 계좌 흐름 기준으로 연결합니다."/></>}
   {view==="settings"&&<><Intro title="GitHub에는 코드만, 영업 데이터는 DB에." copy="V0.1은 DEMO MODE. Supabase 연결 후 두 사람이 같은 데이터를 사용하도록 전환합니다."/><div className="settings"><section className="panel"><Setting title="WEB UI" text="Next.js 반응형 관리자 화면" ok/><Setting title="Excel Export" text="현재 WEB 데이터를 XLSX로 내보내기" ok/><Setting title="Supabase" text="SQL 스키마 포함 · 연결 전"/></section><section className="panel"><Head over="DEPLOYMENT" title="임시도메인 운영"/><div className="deploy"><span>GitHub</span>→<span>Vercel</span>→<span>*.vercel.app</span></div><p>도메인 확보 뒤 admin.smeverflow.kr 같은 주소만 연결하면 됩니다.</p></section></div></>}
  </div></main>
  {modal==="product"&&<Modal title="빠른 매입 등록" onClose={()=>setModal(null)}><form onSubmit={e=>{e.preventDefault();addProduct(new FormData(e.currentTarget))}}><div className="auto"><span>다음 상품ID</span><b>SME-2608-{String(products.length+1).padStart(4,"0")}</b></div><div className="formGrid"><label>매입유형<select name="purchaseType"><option>국내현금매입</option><option>일본직접매입</option><option>일본경매직구</option><option>일본온라인직구</option></select></label><label>브랜드<input name="brand" required placeholder="Max Mara"/></label><label>품목<select name="category"><option>원피스</option><option>자켓</option><option>니트</option><option>탑</option><option>셋업</option><option>기타</option></select></label><label>현재 확인 매입비<input name="cost" type="number" placeholder="120000"/></label></div><label>상품명<input name="name" required placeholder="실크 체크 원피스"/></label><label>배치ID (선택)<input name="batch" placeholder="미입력 시 현장배치 자동"/></label><div className="modalActions"><button type="button" className="btn light" onClick={()=>setModal(null)}>취소</button><button className="btn dark"><Plus size={16}/>상품 생성</button></div></form></Modal>}
  {modal==="sale"&&<Modal title="판매·정산 입력" onClose={()=>setModal(null)}><form onSubmit={e=>{e.preventDefault();addSale(new FormData(e.currentTarget))}}><label>상품<select name="productId">{inv.map(p=><option key={p.id} value={p.id}>{p.id} · {p.brand} · {p.name}</option>)}</select></label><div className="formGrid"><label>판매채널<select name="channel"><option>당근마켓</option><option>번개장터</option><option>스마트스토어</option><option>중고나라</option><option>오프라인도매</option></select></label><label>판매가<input name="gross" type="number" required/></label><label>플랫폼/결제 수수료<input name="fee" type="number" defaultValue="0"/></label><label>판매자 배송비<input name="shipping" type="number" defaultValue="0"/></label></div><div className="modalActions"><button type="button" className="btn light" onClick={()=>setModal(null)}>취소</button><button className="btn dark">판매 처리</button></div></form></Modal>}
 </div>
}
function Intro({title,copy,action}:{title:string;copy:string;action?:React.ReactNode}){return <section className="intro"><div><small>SM EVERFLOW / OPERATIONS</small><h2>{title}</h2><p>{copy}</p></div>{action}</section>}
function Kpi({label,value,note,dark=false}:{label:string;value:string;note:string;dark?:boolean}){return <section className={dark?"kpi dark":"kpi"}><span>{label}</span><b>{value}</b><small>{note}</small></section>}
function Head({over,title}:{over:string;title:string}){return <div className="panelHead"><small>{over}</small><h3>{title}</h3></div>}
function Progress({label,n,pct}:{label:string;n:string;pct:number}){return <div className="progress"><div><span>{label}</span><b>{n}</b></div><i><em style={{width:`${pct}%`}}/></i></div>}
function Table({rows}:{rows:Product[]}){return <div className="tableWrap"><table><thead><tr><th>상품</th><th>상태</th><th>매입유형</th><th>확인 원가</th><th>완전원가</th><th>플랫폼</th><th>배송</th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><div className="prod"><div className="thumb">{p.brand.split(" ").map(x=>x[0]).join("").slice(0,2)}</div><div><small>{p.id}</small><b>{p.brand}</b><span>{p.name}</span></div></div></td><td><span className="pill">{p.status}</span></td><td>{p.purchaseType}</td><td><b>{won(p.cost)}</b><small className="note">현재 확인분</small></td><td><b>{won(p.totalCost)}</b><small className="note">추가비 미반영</small></td><td><span className="mini">{p.platforms.length?p.platforms.join(", "):"미등록"}</span></td><td>{p.ems||"-"}</td></tr>)}</tbody></table></div>}
function Empty({title,copy}:{title:string;copy:string}){return <section className="panel empty"><Store size={28}/><b>{title}</b><span>{copy}</span></section>}
function Setting({title,text,ok=false}:{title:string;text:string;ok?:boolean}){return <div className="setting"><i className={ok?"ok":""}/><div><b>{title}</b><span>{text}</span></div><em>{ok?"완료":"연결대기"}</em></div>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="modalShade" onMouseDown={onClose}><section className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modalHead"><div><small>SM EVERFLOW</small><h3>{title}</h3></div><button onClick={onClose}><X size={18}/></button></div>{children}</section></div>}
