"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {LayoutDashboard,Boxes,ShoppingBag,Store,CreditCard,WalletCards,Settings,Plus,Download,Search,Truck,X,Menu,LogOut,Camera,ImagePlus,UserRound,RefreshCw,ShieldCheck} from "lucide-react";
import * as XLSX from "xlsx";
import type { Session } from "@supabase/supabase-js";
import { supabase } from "@/lib/supabase";

type Status="입고전"|"입고완료"|"촬영대기"|"판매중"|"예약"|"판매완료";
type Product={id:string;batch:string;date:string;brand:string;category:string;name:string;size?:string;color?:string;material?:string;grade?:string;status:Status;purchaseType:string;cost:number;firstPayment?:number;secondPayment?:number;importDuty?:number;importVat?:number;customsFee?:number;otherImportCost?:number;commonCost?:number;totalCost:number;ems?:string;bundle?:string;auction?:string;source?:string;imagePath?:string;platforms:string[]};
type Batch={id:string;purchaseType:string;date:string;source:string;bundle?:string;ems?:string;count:number;cost:number;status:string;note?:string};
type Sale={id:string;productId:string;channel:string;gross:number;fee:number;paymentFee:number;shipping:number;other:number;net:number;settled?:number;status:string;date:string};
type Listing={id:string;productId:string;platform:string;price:number;status:string;url?:string};
type Expense={id:string;date:string;category:string;amount:number;batch?:string;note?:string};
type View="dashboard"|"inventory"|"purchases"|"platforms"|"sales"|"cash"|"settings";
type Role="ADMIN"|"GM"|"CEO";

type UserProfile={loginId:string;name:string;role:Role};
const ACCOUNT_MAP:Record<string,UserProfile>={
  admin:{loginId:"admin",name:"ADMIN",role:"ADMIN"},
  jedilick:{loginId:"jedilick",name:"정환재",role:"GM"},
  susan98302:{loginId:"susan98302",name:"이송민",role:"CEO"},
};
const emailFor=(id:string)=>`${id.toLowerCase()}@smeverflow.com`;
const nav=[["dashboard","대시보드",LayoutDashboard],["inventory","상품·재고",Boxes],["purchases","매입·수입",ShoppingBag],["platforms","플랫폼 등록",Store],["sales","판매·정산",CreditCard],["cash","금전·비용",WalletCards],["settings","설정",Settings]] as const;
const won=(n:number)=>new Intl.NumberFormat("ko-KR",{style:"currency",currency:"KRW",maximumFractionDigits:0}).format(n||0);
const num=(n:number)=>new Intl.NumberFormat("ko-KR").format(n||0);

export default function Page(){
 const [session,setSession]=useState<Session|null>(null),[authLoading,setAuthLoading]=useState(true),[loginId,setLoginId]=useState(""),[password,setPassword]=useState(""),[loginError,setLoginError]=useState("");
 const [view,setView]=useState<View>("dashboard"),[products,setProducts]=useState<Product[]>([]),[batches,setBatches]=useState<Batch[]>([]),[sales,setSales]=useState<Sale[]>([]),[listings,setListings]=useState<Listing[]>([]),[expenses,setExpenses]=useState<Expense[]>([]),[q,setQ]=useState(""),[modal,setModal]=useState<"product"|"sale"|null>(null),[mobile,setMobile]=useState(false),[loading,setLoading]=useState(false),[dataError,setDataError]=useState("");
 const [imageUrls,setImageUrls]=useState<Record<string,string>>({}),[uploadingId,setUploadingId]=useState<string|null>(null);
 const quickFile=useRef<HTMLInputElement|null>(null);

 useEffect(()=>{
   supabase.auth.getSession().then(({data})=>{setSession(data.session);setAuthLoading(false)});
   const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,s)=>{setSession(s);setAuthLoading(false)});
   return()=>subscription.unsubscribe();
 },[]);
 useEffect(()=>{if(session) loadAll(); else {setProducts([]);setBatches([]);setSales([]);setListings([]);setExpenses([])}},[session]);

 const currentId=session?.user.email?.split("@")[0]||"";
 const user=ACCOUNT_MAP[currentId]||{loginId:currentId,name:currentId||"User",role:"GM" as Role};
 const inv=products.filter(p=>p.status!=="판매완료"), total=inv.reduce((a,b)=>a+b.totalCost,0), verified=inv.reduce((a,b)=>a+b.cost,0), gross=sales.reduce((a,b)=>a+b.gross,0), net=sales.reduce((a,b)=>a+(b.settled??b.net),0), pending=sales.filter(s=>s.status!=="정산완료").reduce((a,b)=>a+b.net,0);
 const filtered=useMemo(()=>products.filter(p=>(p.id+" "+p.brand+" "+p.name).toLowerCase().includes(q.toLowerCase())),[products,q]);
 const firstCount=products.filter(p=>(p.firstPayment||0)>0).length, importCount=products.filter(p=>((p.importDuty||0)+(p.importVat||0)+(p.customsFee||0)+(p.otherImportCost||0))>0).length;

 async function login(e:React.FormEvent){e.preventDefault();setLoginError("");const id=loginId.trim().toLowerCase();if(!ACCOUNT_MAP[id]){setLoginError("등록되지 않은 ID입니다.");return}const {error}=await supabase.auth.signInWithPassword({email:emailFor(id),password});if(error)setLoginError("ID 또는 비밀번호를 확인해 주세요.")}
 async function logout(){await supabase.auth.signOut();}
 async function loadAll(){
   setLoading(true);setDataError("");
   const [p,b,s,l,e]=await Promise.all([
     supabase.from("products").select("*").order("created_at",{ascending:false}),
     supabase.from("batches").select("*").order("batch_date",{ascending:false}),
     supabase.from("sales").select("*").order("sold_at",{ascending:false}),
     supabase.from("listings").select("*").order("created_at",{ascending:false}),
     supabase.from("expenses").select("*").order("expense_date",{ascending:false}),
   ]);
   const err=p.error||b.error||s.error||l.error||e.error;if(err){setDataError(err.message);setLoading(false);return}
   const lp=(p.data||[]).map((r:any)=>({id:r.product_id,batch:r.batch_id||"",date:r.purchase_date,brand:r.brand,category:r.category,name:r.product_name,size:r.size||"",color:r.color||"",material:r.material||"",grade:r.grade||"",status:r.inventory_status as Status,purchaseType:r.purchase_type,cost:Number(r.verified_cost||0),firstPayment:r.first_payment?Number(r.first_payment):undefined,secondPayment:r.second_payment?Number(r.second_payment):undefined,importDuty:r.import_duty?Number(r.import_duty):undefined,importVat:r.import_vat?Number(r.import_vat):undefined,customsFee:r.customs_fee?Number(r.customs_fee):undefined,otherImportCost:r.other_import_cost?Number(r.other_import_cost):undefined,commonCost:Number(r.allocated_common_cost||0),totalCost:Number(r.total_cost||0),ems:r.ems||"",bundle:r.bundle_no||"",auction:r.auction_no||"",source:r.source||"",imagePath:r.image_url||"",platforms:[]}));
   const ll=(l.data||[]).map((r:any)=>({id:String(r.listing_id),productId:r.product_id,platform:r.platform,price:Number(r.listing_price||0),status:r.status,url:r.url||""}));
   lp.forEach((x:any)=>x.platforms=ll.filter(y=>y.productId===x.id&&y.status==="판매중").map(y=>y.platform));
   setProducts(lp);setListings(ll);
   setBatches((b.data||[]).map((r:any)=>({id:r.batch_id,purchaseType:r.purchase_type,date:r.batch_date,source:r.source,bundle:r.bundle_no||"",ems:r.tracking_no||"",count:Number(r.product_count||0),cost:Number(r.verified_cost||0),status:r.status,note:r.note||""})));
   setSales((s.data||[]).map((r:any)=>({id:String(r.sale_id),productId:r.product_id,channel:r.platform,gross:Number(r.gross_amount||0),fee:Number(r.platform_fee||0),paymentFee:Number(r.payment_fee||0),shipping:Number(r.shipping_cost||0),other:Number(r.other_cost||0),net:Number(r.expected_settlement||0),settled:r.settled_amount==null?undefined:Number(r.settled_amount),status:r.settlement_status,date:r.sold_at})));
   setExpenses((e.data||[]).map((r:any)=>({id:String(r.expense_id),date:r.expense_date,category:r.category,amount:Number(r.amount||0),batch:r.batch_id||"",note:r.note||""})));
   await hydrateImages(lp);
   setLoading(false);
 }
 async function hydrateImages(rows:Product[]){const entries=await Promise.all(rows.filter(x=>x.imagePath).map(async x=>{const {data}=await supabase.storage.from("product-images").createSignedUrl(x.imagePath!,3600);return [x.id,data?.signedUrl||""] as const}));setImageUrls(Object.fromEntries(entries));}
 async function uploadPhoto(productId:string,file:File){
   if(!file)return;setUploadingId(productId);const ext=(file.name.split(".").pop()||"jpg").toLowerCase();const path=`${productId}/${Date.now()}.${ext}`;
   const {error}=await supabase.storage.from("product-images").upload(path,file,{upsert:false,contentType:file.type||undefined});if(error){alert(`사진 업로드 실패: ${error.message}`);setUploadingId(null);return}
   const {error:up}=await supabase.from("products").update({image_url:path,updated_at:new Date().toISOString()}).eq("product_id",productId);if(up){alert(`상품 연결 실패: ${up.message}`);setUploadingId(null);return}
   const {data}=await supabase.storage.from("product-images").createSignedUrl(path,3600);setImageUrls(v=>({...v,[productId]:data?.signedUrl||URL.createObjectURL(file)}));setProducts(v=>v.map(p=>p.id===productId?{...p,imagePath:path}:p));setUploadingId(null);
 }
 function nextProductId(){const ym=new Date().toISOString().slice(2,7).replace("-","");const max=products.map(p=>Number(p.id.split("-").pop())||0).reduce((a,b)=>Math.max(a,b),0);return `SME-${ym}-${String(max+1).padStart(4,"0")}`}
 async function addProduct(fd:FormData){
   const id=nextProductId(),cost=Number(fd.get("cost")||0),purchaseType=String(fd.get("purchaseType")||"국내현금매입"),batch=String(fd.get("batch")||`FIELD-${new Date().toISOString().slice(2,10).replaceAll("-","")}`),date=new Date().toISOString().slice(0,10);
   const row={product_id:id,batch_id:null,purchase_date:date,purchase_type:purchaseType,brand:String(fd.get("brand")||""),category:String(fd.get("category")||"기타"),product_name:String(fd.get("name")||""),size:String(fd.get("size")||"")||null,color:String(fd.get("color")||"")||null,inventory_status:purchaseType.includes("일본")?"입고전":"입고완료",source:String(fd.get("source")||"")||null,verified_cost:cost,second_payment:purchaseType.includes("경매")?cost:null,total_cost:cost,note:`WEB 등록 / 현장배치 ${batch}`};
   const {error}=await supabase.from("products").insert(row);if(error){alert(`상품 등록 실패: ${error.message}`);return}
   const file=quickFile.current?.files?.[0];if(file)await uploadPhoto(id,file);setModal(null);await loadAll();
 }
 async function addSale(fd:FormData){
   const productId=String(fd.get("productId")),g=Number(fd.get("gross")||0),fee=Number(fd.get("fee")||0),pay=Number(fd.get("paymentFee")||0),ship=Number(fd.get("shipping")||0),other=Number(fd.get("other")||0),channel=String(fd.get("channel")||"기타"),expected=Math.max(0,g-fee-pay-ship-other),status=String(fd.get("settlementStatus")||"정산대기");
   const {error}=await supabase.from("sales").insert({product_id:productId,platform:channel,sold_at:new Date().toISOString().slice(0,10),gross_amount:g,platform_fee:fee,payment_fee:pay,shipping_cost:ship,other_cost:other,expected_settlement:expected,settled_amount:status==="정산완료"?expected:null,settlement_status:status});if(error){alert(`판매 등록 실패: ${error.message}`);return}
   await supabase.from("products").update({inventory_status:"판매완료",sold_price:g,updated_at:new Date().toISOString()}).eq("product_id",productId);
   setModal(null);await loadAll();
 }
 function excel(){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([["SM EVERFLOW | WEB EXPORT"],["현재 재고",inv.length],["현재 확인 원가",verified],["재고 관리완전원가",total],["누적 판매총액",gross],["실제 정산액",net],["미정산",pending]]),"01_대시보드");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(products.map(p=>({상품ID:p.id,배치ID:p.batch,매입일:p.date,매입유형:p.purchaseType,브랜드:p.brand,품목:p.category,상세명:p.name,사이즈:p.size||"",컬러:p.color||"",상태:p.status,현재확인원가:p.cost,"1차결제":p.firstPayment||"","2차결제":p.secondPayment||"",관세:p.importDuty||"",수입VAT:p.importVat||"",통관수수료:p.customsFee||"",기타수입비:p.otherImportCost||"",공통비:p.commonCost||0,경영관리완전원가:p.totalCost,EMS:p.ems||"",묶음번호:p.bundle||"",경매번호:p.auction||"",등록플랫폼:p.platforms.join(", "),사진경로:p.imagePath||""}))),"02_상품마스터");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(batches),"03_배치마스터");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(listings),"07_플랫폼등록");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(sales),"08_매출정산");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(expenses),"06_공통비용");XLSX.writeFile(wb,`SM_EVERFLOW_WEB_EXPORT_${new Date().toISOString().slice(0,10).replaceAll("-","")}.xlsx`)}

 if(authLoading)return <div className="authPage"><div className="authCard"><div className="mark">SM</div><h1>SM EVERFLOW</h1><p>인증 상태를 확인하고 있습니다.</p></div></div>;
 if(!session)return <div className="authPage"><form className="authCard" onSubmit={login}><div className="authBrand"><div className="mark">SM</div><div><b>EVERFLOW</b><span>PRIVATE OPERATIONS</span></div></div><small>PRIVATE ADMIN</small><h1>운영 시스템 로그인</h1><p>허가된 사용자만 접근할 수 있습니다.</p><label>ID<input value={loginId} onChange={e=>setLoginId(e.target.value)} autoComplete="username" placeholder="ID" required/></label><label>PASSWORD<input value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" type="password" placeholder="••••••••" required/></label>{loginError&&<div className="authError">{loginError}</div>}<button className="btn dark authSubmit"><ShieldCheck size={17}/>로그인</button></form></div>;

 return <div className="shell">
  <aside className={mobile?"open":""}><div className="brand"><div className="mark">SM</div><div><b>EVERFLOW</b><span>PRIVATE OPERATIONS</span></div><button onClick={()=>setMobile(false)}><X size={18}/></button></div><nav>{nav.map(([id,label,Icon])=><button className={view===id?"active":""} key={id} onClick={()=>{setView(id);setMobile(false)}}><Icon size={17}/><span>{label}</span>{id==="inventory"&&<em>{inv.length}</em>}</button>)}</nav><div className="mode online"><i/><div><b>ONLINE DATABASE</b><span>Supabase 실시간 운영</span></div></div><button className="sideUser" onClick={logout}><UserRound size={16}/><div><b>{user.name} · {user.role}</b><span>{user.loginId}</span></div><LogOut size={15}/></button></aside>
  {mobile&&<div className="shade" onClick={()=>setMobile(false)}/>}<main><header><div className="title"><button onClick={()=>setMobile(true)}><Menu size={20}/></button><div><small>SM EVERFLOW / OPERATIONS</small><h1>{nav.find(n=>n[0]===view)?.[1]}</h1></div></div><div className="actions"><button className="btn light" onClick={loadAll} title="새로고침"><RefreshCw size={16}/></button><button className="btn light" onClick={excel}><Download size={16}/>Excel</button><button className="btn dark" onClick={()=>setModal("product")}><Plus size={16}/>빠른 매입</button></div></header>
  <div className="content">{dataError&&<div className="errorBanner">DB 오류: {dataError}</div>}{loading&&<div className="loadingBar">온라인 데이터를 불러오는 중...</div>}
   {view==="dashboard"&&<><Intro title="오늘의 운영 현황" copy="재고 수량보다 상품별 상태와 원가 완성도를 먼저 봅니다."/><div className="kpis"><Kpi dark label="현재 재고" value={`${inv.length}점`} note={`${inv.filter(p=>p.status==="입고전").length}점 국제배송중`}/><Kpi label="현재 확인 원가" value={won(verified)} note="확인된 직접비 합계"/><Kpi label="관리 완전원가" value={won(total)} note="공통비·통관비 포함 관리값"/><Kpi label="활성 판매등록" value={`${listings.filter(x=>x.status==="판매중").length}건`} note="플랫폼별 게시물"/><Kpi label="누적 판매" value={won(gross)} note={`실제정산 ${won(net)}`}/><Kpi label="미정산" value={won(pending)} note="플랫폼별 정산 추적"/></div><div className="grid"><section className="panel"><Head over="INBOUND" title="일본 → 한국 입고 예정"/>{batches.filter(b=>b.status!=="입고완료").map(b=><div className="ship" key={b.id}><div className="shipIcon"><Truck size={18}/></div><div><b>{b.id}</b><span className="pill">{b.status}</span><small>묶음 {b.bundle||"-"} · EMS {b.ems||"-"}</small></div><div className="shipValue"><b>{b.count}점</b><span>{won(b.cost)}</span></div></div>)}</section><section className="panel"><Head over="COST COMPLETENESS" title="원가 완성도"/><Progress label="2차결제 확인" n={`${products.filter(p=>(p.secondPayment||p.cost)>0).length}/${products.length}`} pct={products.length?100*products.filter(p=>(p.secondPayment||p.cost)>0).length/products.length:0}/><Progress label="1차결제 입력" n={`${firstCount}/${products.length}`} pct={products.length?100*firstCount/products.length:0}/><Progress label="통관비 확정" n={`${importCount}/${products.length}`} pct={products.length?100*importCount/products.length:0}/><div className="notice"><b>완전원가는 입력된 근거만 반영됩니다.</b><span>1차결제·관세·수입VAT·공통비가 들어오면 상품별 원가를 지속적으로 보완합니다.</span></div></section></div><section className="panel tablePanel"><Head over="RECENT INVENTORY" title="최근 상품"/><Table rows={products.slice(0,6)} imageUrls={imageUrls} onPhoto={uploadPhoto} uploadingId={uploadingId}/></section></>}
   {view==="inventory"&&<><Intro title="상품 하나를 끝까지 추적합니다." copy="실물 한 점마다 상품ID 하나. 사진·매입·게시·판매·정산이 이 ID에 붙습니다." action={<button className="btn light" onClick={()=>setModal("product")}><Camera size={16}/>사진 포함 현장매입</button>}/><div className="toolbar"><div><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="상품ID, 브랜드, 상품명 검색"/></div><span>{filtered.length}개 상품</span></div><section className="panel tablePanel"><Table rows={filtered} imageUrls={imageUrls} onPhoto={uploadPhoto} uploadingId={uploadingId}/></section></>}
   {view==="purchases"&&<><Intro title="상품과 배치를 동시에 봅니다." copy="EMS 한 묶음, 일본 출장 한 번, 국내 현금매입 묶음을 각각 비용 단위로 관리합니다."/><div className="batchGrid">{batches.map(b=><section className="panel" key={b.id}><div className="batchTop"><div><small>{b.id}</small><h3>{b.source}</h3></div><span className="pill">{b.status}</span></div><div className="route"><span>매입/출고</span><i/><Truck size={17}/><i/><span>입고</span></div><div className="stats"><div><span>묶음</span><b>{b.bundle||"-"}</b></div><div><span>EMS</span><b>{b.ems||"-"}</b></div><div><span>상품</span><b>{b.count}점</b></div><div><span>확인원가</span><b>{won(b.cost)}</b></div></div>{b.note&&<div className="warn">{b.note}</div>}</section>)}</div></>}
   {view==="platforms"&&<><Intro title="상품 1개, 게시물은 여러 개." copy="스마트스토어·당근·번개·중고나라에 올라간 게시물을 상품ID로 연결합니다."/><div className="platforms">{["스마트스토어","당근마켓","번개장터","중고나라","오프라인도매"].map(x=><section className="panel" key={x}><span>{x}</span><b>{listings.filter(l=>l.platform===x&&l.status==="판매중").length}</b><small>판매중</small></section>)}</div>{listings.length===0?<Empty title="아직 등록된 판매 게시물이 없습니다." copy="입고 후 게시물을 추가하면 상품ID 기준으로 관리합니다."/>:<section className="panel tablePanel"><div className="tableWrap"><table><thead><tr><th>상품ID</th><th>플랫폼</th><th>등록가</th><th>상태</th><th>URL</th></tr></thead><tbody>{listings.map(l=><tr key={l.id}><td>{l.productId}</td><td>{l.platform}</td><td>{won(l.price)}</td><td>{l.status}</td><td>{l.url||"-"}</td></tr>)}</tbody></table></div></section>}</>}
   {view==="sales"&&<><Intro title="판매가와 실제 입금액은 분리합니다." copy="플랫폼 수수료·결제수수료·배송비를 빼고 실제 정산액까지 추적합니다." action={<button className="btn dark" onClick={()=>setModal("sale")}><Plus size={16}/>판매 입력</button>}/>{sales.length===0?<Empty title="아직 판매 데이터가 없습니다." copy="첫 판매부터 입력하면 원가 대비 실제 마진을 추적합니다."/>:<section className="panel tablePanel"><div className="tableWrap"><table><thead><tr><th>상품ID</th><th>채널</th><th>판매가</th><th>플랫폼비</th><th>결제비</th><th>배송비</th><th>예상정산</th><th>상태</th></tr></thead><tbody>{sales.map(s=><tr key={s.id}><td>{s.productId}</td><td>{s.channel}</td><td>{won(s.gross)}</td><td>{won(s.fee)}</td><td>{won(s.paymentFee)}</td><td>{won(s.shipping)}</td><td><b>{won(s.settled??s.net)}</b></td><td>{s.status}</td></tr>)}</tbody></table></div></section>}</>}
   {view==="cash"&&<><Intro title="실제 돈의 흐름을 놓치지 않습니다." copy="실제 출금·입금과 세무상 처리는 분리해서 기록합니다."/><div className="kpis three"><Kpi dark label="확인 매입지출" value={won(verified)} note="현재 확인된 직접비"/><Kpi label="판매 정산입금" value={won(net)} note="실제/예상 정산 누계"/><Kpi label="공통비용" value={won(expenses.reduce((a,b)=>a+b.amount,0))} note="출장·숙박·교통·기타"/></div>{expenses.length===0?<Empty title="공통비 내역이 아직 없습니다." copy="일본 출장비와 국내 현금매입 관련 비용을 배치와 연결해 관리합니다."/>:<section className="panel tablePanel"><div className="tableWrap"><table><thead><tr><th>일자</th><th>구분</th><th>금액</th><th>배치</th><th>비고</th></tr></thead><tbody>{expenses.map(e=><tr key={e.id}><td>{e.date}</td><td>{e.category}</td><td>{won(e.amount)}</td><td>{e.batch||"-"}</td><td>{e.note||"-"}</td></tr>)}</tbody></table></div></section>}</>}
   {view==="settings"&&<><Intro title="실제 운영 DB와 인증이 연결되었습니다." copy="GitHub에는 코드만 두고, 상품·매출·사진은 Supabase에 저장합니다."/><div className="settings"><section className="panel"><Setting title="Supabase Auth" text={`${user.name} / ${user.role} 로그인 중`} ok/><Setting title="Supabase Database" text={`${products.length}개 상품 · ${batches.length}개 배치`} ok/><Setting title="Product Images" text="비공개 Storage / 로그인 사용자만 접근" ok/><Setting title="Excel Export" text="현재 온라인 데이터를 XLSX로 내보내기" ok/></section><section className="panel"><Head over="ACCOUNT" title="현재 사용자"/><div className="accountCard"><UserRound size={24}/><b>{user.name}</b><span>{user.role} · {user.loginId}</span><button className="btn light" onClick={logout}><LogOut size={15}/>로그아웃</button></div></section></div></>}
  </div></main>
  {modal==="product"&&<Modal title="빠른 매입 등록" onClose={()=>setModal(null)}><form onSubmit={e=>{e.preventDefault();addProduct(new FormData(e.currentTarget))}}><div className="auto"><span>다음 상품ID</span><b>{nextProductId()}</b></div><div className="photoDrop"><ImagePlus size={22}/><div><b>상품 사진</b><span>휴대폰에서는 카메라로 바로 촬영할 수 있습니다.</span></div><input ref={quickFile} name="photo" type="file" accept="image/*" capture="environment"/></div><div className="formGrid"><label>매입유형<select name="purchaseType"><option>국내현금매입</option><option>일본직접매입</option><option>일본경매직구</option><option>일본온라인직구</option></select></label><label>브랜드<input name="brand" required placeholder="Max Mara"/></label><label>품목<select name="category"><option>원피스</option><option>자켓</option><option>니트</option><option>탑</option><option>셋업</option><option>스커트</option><option>팬츠</option><option>기타</option></select></label><label>현재 확인 매입비<input name="cost" type="number" placeholder="120000"/></label><label>사이즈<input name="size" placeholder="38 / M"/></label><label>컬러<input name="color" placeholder="블랙"/></label></div><label>상품명<input name="name" required placeholder="실크 체크 원피스"/></label><div className="formGrid"><label>공급처/거래처<input name="source" placeholder="청계천 / 일본 매장명"/></label><label>배치 메모<input name="batch" placeholder="선택 입력"/></label></div><div className="modalActions"><button type="button" className="btn light" onClick={()=>setModal(null)}>취소</button><button className="btn dark"><Plus size={16}/>상품 생성</button></div></form></Modal>}
  {modal==="sale"&&<Modal title="판매·정산 입력" onClose={()=>setModal(null)}><form onSubmit={e=>{e.preventDefault();addSale(new FormData(e.currentTarget))}}><label>상품<select name="productId">{inv.map(p=><option key={p.id} value={p.id}>{p.id} · {p.brand} · {p.name}</option>)}</select></label><div className="formGrid"><label>판매채널<select name="channel"><option>당근마켓</option><option>번개장터</option><option>스마트스토어</option><option>중고나라</option><option>오프라인도매</option></select></label><label>판매가<input name="gross" type="number" required/></label><label>플랫폼 수수료<input name="fee" type="number" defaultValue="0"/></label><label>결제 수수료<input name="paymentFee" type="number" defaultValue="0"/></label><label>판매자 배송비<input name="shipping" type="number" defaultValue="0"/></label><label>기타 판매비<input name="other" type="number" defaultValue="0"/></label></div><label>정산상태<select name="settlementStatus"><option>정산대기</option><option>정산완료</option></select></label><div className="modalActions"><button type="button" className="btn light" onClick={()=>setModal(null)}>취소</button><button className="btn dark">판매 처리</button></div></form></Modal>}
 </div>
}
function Intro({title,copy,action}:{title:string;copy:string;action?:React.ReactNode}){return <section className="intro"><div><small>SM EVERFLOW / OPERATIONS</small><h2>{title}</h2><p>{copy}</p></div>{action}</section>}
function Kpi({label,value,note,dark=false}:{label:string;value:string;note:string;dark?:boolean}){return <section className={dark?"kpi dark":"kpi"}><span>{label}</span><b>{value}</b><small>{note}</small></section>}
function Head({over,title}:{over:string;title:string}){return <div className="panelHead"><small>{over}</small><h3>{title}</h3></div>}
function Progress({label,n,pct}:{label:string;n:string;pct:number}){return <div className="progress"><div><span>{label}</span><b>{n}</b></div><i><em style={{width:`${Math.max(0,Math.min(100,pct))}%`}}/></i></div>}
function Table({rows,imageUrls,onPhoto,uploadingId}:{rows:Product[];imageUrls:Record<string,string>;onPhoto:(id:string,file:File)=>void;uploadingId:string|null}){return <div className="tableWrap"><table><thead><tr><th>상품</th><th>상태</th><th>매입유형</th><th>확인 원가</th><th>완전원가</th><th>플랫폼</th><th>배송</th><th>사진</th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><div className="prod"><div className="thumb">{imageUrls[p.id]?<img src={imageUrls[p.id]} alt=""/>:p.brand.split(" ").map(x=>x[0]).join("").slice(0,2)}</div><div><small>{p.id}</small><b>{p.brand}</b><span>{p.name}</span></div></div></td><td><span className="pill">{p.status}</span></td><td>{p.purchaseType}</td><td><b>{won(p.cost)}</b><small className="note">현재 확인분</small></td><td><b>{won(p.totalCost)}</b><small className="note">관리 완전원가</small></td><td><span className="mini">{p.platforms.length?p.platforms.join(", "):"미등록"}</span></td><td>{p.ems||"-"}</td><td><label className="photoButton">{uploadingId===p.id?"업로드중":"사진"}<input type="file" accept="image/*" capture="environment" onChange={e=>{const f=e.target.files?.[0];if(f)onPhoto(p.id,f);e.currentTarget.value=""}}/></label></td></tr>)}</tbody></table></div>}
function Empty({title,copy}:{title:string;copy:string}){return <section className="panel empty"><Store size={28}/><b>{title}</b><span>{copy}</span></section>}
function Setting({title,text,ok=false}:{title:string;text:string;ok?:boolean}){return <div className="setting"><i className={ok?"ok":""}/><div><b>{title}</b><span>{text}</span></div><em>{ok?"완료":"연결대기"}</em></div>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="modalShade" onMouseDown={onClose}><section className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modalHead"><div><small>SM EVERFLOW</small><h3>{title}</h3></div><button onClick={onClose}><X size={18}/></button></div>{children}</section></div>}
