-- SM EVERFLOW v0.6.0 — Japan purchase inbox / pre-batch asset tracking
-- Tracks purchased items before they are grouped into an international-shipping batch.

create table if not exists public.purchase_inbox (
  item_id bigint generated by default as identity primary key,
  source_system text not null default 'merujg',
  external_id text not null,
  purchase_method text not null default '일본경매직구',
  status text not null default '구매확정',
  purchase_at timestamptz,
  brand text,
  category text not null default '기타',
  product_name text not null,
  auction_no text,
  seller_name text,
  pure_item_price_jpy numeric not null default 0,
  first_payment_krw numeric not null default 0,
  local_weight_g numeric not null default 0,
  local_shipping_date date,
  warehouse_arrived_at timestamptz,
  source_note text,
  data_quality text not null default 'manual',
  batch_id text references public.batches(batch_id) on update cascade on delete set null,
  product_id text references public.products(product_id) on update cascade on delete set null,
  converted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(source_system, external_id)
);

create index if not exists purchase_inbox_status_idx on public.purchase_inbox(status, created_at desc);
create index if not exists purchase_inbox_batch_idx on public.purchase_inbox(batch_id);
create index if not exists purchase_inbox_product_idx on public.purchase_inbox(product_id);

alter table public.purchase_inbox enable row level security;
drop policy if exists auth_all_purchase_inbox on public.purchase_inbox;
create policy auth_all_purchase_inbox on public.purchase_inbox
  for all to authenticated using (true) with check (true);

create or replace function public.purchase_inbox_before_write()
returns trigger language plpgsql security invoker set search_path=public as $$
begin
  new.updated_at := now();
  if new.status='현지배송완료' and new.warehouse_arrived_at is null then
    new.warehouse_arrived_at := now();
  end if;
  return new;
end; $$;

drop trigger if exists trg_purchase_inbox_before_write on public.purchase_inbox;
create trigger trg_purchase_inbox_before_write
before insert or update on public.purchase_inbox
for each row execute function public.purchase_inbox_before_write();

create or replace function public.log_purchase_inbox_status_event()
returns trigger language plpgsql security invoker set search_path=public as $$
begin
  if tg_op='UPDATE' and old.status is distinct from new.status then
    insert into public.status_events(entity_type,entity_id,from_status,to_status,note,actor_email)
    values('purchase_inbox',new.external_id,old.status,new.status,'일본 구매대기함',auth.jwt()->>'email');
  end if;
  return new;
end; $$;

drop trigger if exists trg_purchase_inbox_log_status on public.purchase_inbox;
create trigger trg_purchase_inbox_log_status
after update of status on public.purchase_inbox
for each row execute function public.log_purchase_inbox_status_event();

-- Convert selected pre-batch purchases into one international-shipping batch and real product records atomically.
create or replace function public.create_batch_from_purchase_inbox(
  p_item_ids bigint[],
  p_batch_id text,
  p_batch_date date,
  p_tracking_no text default null,
  p_carrier text default 'EMS',
  p_bundle_no text default null,
  p_note text default null
)
returns jsonb
language plpgsql
security invoker
set search_path=public
as $$
declare
  r record;
  v_count int := 0;
  v_seq int;
  v_ym text := to_char(p_batch_date,'YYMM');
  v_product_id text;
  v_source text := '메루카리/Japan auction';
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  if p_item_ids is null or cardinality(p_item_ids)=0 then raise exception 'NO_ITEMS_SELECTED'; end if;
  if p_batch_id is null or btrim(p_batch_id)='' then raise exception 'BATCH_ID_REQUIRED'; end if;

  perform pg_advisory_xact_lock(hashtext('sm_everflow_product_id'));

  if exists(select 1 from public.batches where batch_id=p_batch_id) then
    raise exception 'BATCH_ID_ALREADY_EXISTS: %', p_batch_id;
  end if;

  if exists(
    select 1 from public.purchase_inbox
    where item_id=any(p_item_ids)
      and (converted_at is not null or product_id is not null or status='배치전환완료')
  ) then
    raise exception 'ALREADY_CONVERTED_ITEM_INCLUDED';
  end if;

  select count(*) into v_count
  from public.purchase_inbox
  where item_id=any(p_item_ids)
    and status in ('현지배송완료','대행창고보관','묶음배송선택','2차결제대기');

  if v_count <> cardinality(p_item_ids) then
    raise exception 'INVALID_OR_MISSING_ITEMS';
  end if;

  insert into public.batches(
    batch_id,purchase_type,batch_date,source,bundle_no,tracking_no,status,carrier,
    expected_product_count,purchase_currency,purchase_amount_local,note
  )
  select
    p_batch_id,'일본경매직구',p_batch_date,v_source,p_bundle_no,p_tracking_no,
    case when coalesce(p_tracking_no,'')<>'' then '국제배송중' else '출고대기' end,
    p_carrier,v_count,'JPY',coalesce(sum(pure_item_price_jpy),0),p_note
  from public.purchase_inbox where item_id=any(p_item_ids);

  select coalesce(max((regexp_match(product_id,'-([0-9]{4})$'))[1]::int),0)
    into v_seq
  from public.products
  where product_id like ('SME-'||v_ym||'-%');

  for r in
    select * from public.purchase_inbox
    where item_id=any(p_item_ids)
    order by item_id
  loop
    v_seq := v_seq + 1;
    v_product_id := 'SME-'||v_ym||'-'||lpad(v_seq::text,4,'0');

    insert into public.products(
      product_id,batch_id,purchase_date,purchase_type,brand,category,product_name,
      inventory_status,logistics_status,source,auction_no,verified_cost,first_payment,total_cost,note
    ) values (
      v_product_id,p_batch_id,coalesce(r.purchase_at::date,p_batch_date),r.purchase_method,
      coalesce(nullif(r.brand,''),'미확인'),coalesce(nullif(r.category,''),'기타'),r.product_name,
      '입고전',case when coalesce(p_tracking_no,'')<>'' then '국제배송중' else '출고대기' end,
      v_source,r.auction_no,r.first_payment_krw,nullif(r.first_payment_krw,0),r.first_payment_krw,
      concat('Purchase Inbox #',r.external_id,case when r.source_note is not null then ' · '||r.source_note else '' end)
    );

    update public.purchase_inbox
       set status='배치전환완료',batch_id=p_batch_id,product_id=v_product_id,converted_at=now()
     where item_id=r.item_id;
  end loop;

  return jsonb_build_object('batch_id',p_batch_id,'product_count',v_count);
end; $$;

revoke all on function public.create_batch_from_purchase_inbox(bigint[],text,date,text,text,text,text) from public;
grant execute on function public.create_batch_from_purchase_inbox(bigint[],text,date,text,text,text,text) to authenticated;

-- Current user-provided screenshots (2026-08-19). Data is intentionally conservative where text is ambiguous.
insert into public.purchase_inbox(
  source_system,external_id,purchase_method,status,purchase_at,brand,category,product_name,auction_no,
  pure_item_price_jpy,first_payment_krw,local_weight_g,local_shipping_date,source_note,data_quality
) values
('merujg','196337','일본경매직구','1차결제완료','2026-08-16 21:44:34+09','Max Mara','니트','Max Mara 니트 · 꽃장식 · 화이트 · M','n1235330013',3500,47124,0,null,'2026-08-19 사용자 제공 대행사이트 캡처 기반 초기입력','capture'),
('merujg','196262','일본경매직구','1차결제완료','2026-08-12 23:09:33+09','Max Mara','원피스','Max Mara 원피스 · 허리끈 · 2608r1','b1239239617',5800,77792,0,null,'2026-08-19 사용자 제공 대행사이트 캡처 기반 초기입력','capture'),
('merujg','196457','일본경매직구','현지배송완료',null,'NINA RICCI','가방','NINA RICCI 숄더백 · 브라운/베이지','p1239256307',800,15216,800,'2026-08-15','2026-08-19 사용자 제공 대행사이트 캡처 기반 초기입력','capture'),
('merujg','196176','일본경매직구','현지배송완료',null,'ENFOLD','스커트','ENFOLD 셔링 롱스커트 · 블랙 · 36',null,6900,65895,800,'2026-08-15','2026-08-19 사용자 제공 대행사이트 캡처 기반 초기입력','capture'),
('merujg','196332','일본경매직구','현지배송완료',null,'Max Mara','블라우스','Max Mara WEEKEND 니트 블라우스', 'c1239266345',2600,34917,200,'2026-08-18','2026-08-19 사용자 제공 대행사이트 캡처 기반 초기입력','capture')
on conflict(source_system,external_id) do update set
  status=excluded.status,
  brand=coalesce(nullif(public.purchase_inbox.brand,''),excluded.brand),
  category=case when public.purchase_inbox.category='기타' then excluded.category else public.purchase_inbox.category end,
  product_name=case when public.purchase_inbox.product_name='' then excluded.product_name else public.purchase_inbox.product_name end,
  auction_no=coalesce(public.purchase_inbox.auction_no,excluded.auction_no),
  pure_item_price_jpy=case when public.purchase_inbox.pure_item_price_jpy=0 then excluded.pure_item_price_jpy else public.purchase_inbox.pure_item_price_jpy end,
  first_payment_krw=case when public.purchase_inbox.first_payment_krw=0 then excluded.first_payment_krw else public.purchase_inbox.first_payment_krw end,
  local_weight_g=case when public.purchase_inbox.local_weight_g=0 then excluded.local_weight_g else public.purchase_inbox.local_weight_g end,
  local_shipping_date=coalesce(public.purchase_inbox.local_shipping_date,excluded.local_shipping_date),
  updated_at=now();
