-- SM EVERFLOW v0.5.0
-- Operational batch intake, product photo gallery, and platform account profiles.

alter table public.batches add column if not exists expected_product_count integer not null default 0;
alter table public.batches add column if not exists purchase_currency text not null default 'KRW';
alter table public.batches add column if not exists purchase_amount_local numeric not null default 0;
alter table public.batches add column if not exists fx_rate numeric not null default 0;

update public.batches
set expected_product_count = case when expected_product_count=0 then product_count else expected_product_count end,
    purchase_currency = case when purchase_type like '일본%' then 'JPY' else coalesce(nullif(purchase_currency,''),'KRW') end;

create table if not exists public.product_images (
  image_id bigint generated by default as identity primary key,
  product_id text not null references public.products(product_id) on delete cascade,
  storage_path text not null unique,
  original_name text,
  mime_type text,
  size_bytes bigint,
  sort_order integer not null default 0,
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists product_images_product_idx on public.product_images(product_id, sort_order, image_id);
create unique index if not exists product_images_one_primary_idx on public.product_images(product_id) where is_primary;
alter table public.product_images enable row level security;
drop policy if exists auth_all_product_images on public.product_images;
create policy auth_all_product_images on public.product_images for all to authenticated using (true) with check (true);

create or replace function public.product_images_before_write()
returns trigger language plpgsql security invoker set search_path=public as $$
declare image_count integer;
begin
  if tg_op='INSERT' then
    select count(*) into image_count from public.product_images where product_id=new.product_id;
    if image_count >= 10 then
      raise exception '상품당 사진은 최대 10장까지 등록할 수 있습니다.';
    end if;
    if not exists(select 1 from public.product_images where product_id=new.product_id and is_primary) then
      new.is_primary := true;
    end if;
  end if;
  if new.is_primary then
    update public.product_images set is_primary=false, updated_at=now()
    where product_id=new.product_id and image_id is distinct from new.image_id and is_primary=true;
  end if;
  new.updated_at:=now();
  return new;
end; $$;

drop trigger if exists trg_product_images_before_write on public.product_images;
create trigger trg_product_images_before_write before insert or update on public.product_images
for each row execute function public.product_images_before_write();

create or replace function public.sync_product_primary_image()
returns trigger language plpgsql security invoker set search_path=public as $$
declare pid text; chosen text;
begin
  pid := case when tg_op='DELETE' then old.product_id else new.product_id end;
  select storage_path into chosen from public.product_images where product_id=pid
  order by is_primary desc, sort_order asc, image_id asc limit 1;
  update public.products set image_url=chosen, updated_at=now() where product_id=pid;
  if tg_op='DELETE' then return old; else return new; end if;
end; $$;

drop trigger if exists trg_product_images_sync_product on public.product_images;
create trigger trg_product_images_sync_product after insert or update or delete on public.product_images
for each row execute function public.sync_product_primary_image();

insert into public.product_images(product_id,storage_path,sort_order,is_primary)
select p.product_id,p.image_url,0,true from public.products p
where p.image_url is not null and p.image_url<>''
  and not exists(select 1 from public.product_images i where i.product_id=p.product_id and i.storage_path=p.image_url)
on conflict(storage_path) do nothing;

create table if not exists public.platform_accounts (
  platform text primary key,
  store_name text,
  login_id text,
  profile_code text,
  joined_at date,
  verified boolean not null default false,
  active boolean not null default true,
  priority integer not null default 50,
  metrics jsonb not null default '{}'::jsonb,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.platform_accounts enable row level security;
drop policy if exists auth_all_platform_accounts on public.platform_accounts;
create policy auth_all_platform_accounts on public.platform_accounts for all to authenticated using (true) with check (true);

insert into public.platform_accounts(platform,store_name,login_id,profile_code,joined_at,verified,active,priority,metrics,note)
values
('당근마켓','마틴코코',null,'#DQ968Z4Q','2025-07-02',true,true,10,
 jsonb_build_object('manner_temp',53.1,'resale_hope_pct',94,'response_rate_pct',100,'sales_items',319,'pay_verified',true,'neighborhood','서초동 6회, 서울 용산구 30회'),
 '본인인증·당근페이 인증 완료'),
('번개장터','마틴코코','010-7768-6755',null,null,true,true,10,
 jsonb_build_object('rating',5.0,'followers',421,'following',0,'products',797,'safe_pay',319,'open_days',2132,'badges',3),
 '프로 상점 · 본인인증 완료'),
('필웨이',null,null,null,null,false,false,90,'{}'::jsonb,'현재 판매 효율이 낮아 저우선 채널')
on conflict(platform) do update set
 store_name=excluded.store_name,
 login_id=coalesce(excluded.login_id,public.platform_accounts.login_id),
 profile_code=coalesce(excluded.profile_code,public.platform_accounts.profile_code),
 joined_at=coalesce(excluded.joined_at,public.platform_accounts.joined_at),
 verified=excluded.verified,
 active=excluded.active,
 priority=excluded.priority,
 metrics=excluded.metrics,
 note=excluded.note,
 updated_at=now();
