-- SM EVERFLOW v0.4.0 operational workflow
-- Applied to production on 2026-08-19.

alter table public.batches add column if not exists status_updated_at timestamptz not null default now();
alter table public.batches add column if not exists customs_entered_at timestamptz;
alter table public.batches add column if not exists customs_cleared_at timestamptz;
alter table public.batches add column if not exists received_at timestamptz;
alter table public.batches add column if not exists carrier text default 'EMS';
alter table public.batches add column if not exists domestic_tracking_no text;
alter table public.batches add column if not exists international_shipping numeric not null default 0;
alter table public.batches add column if not exists service_fee numeric not null default 0;
alter table public.batches add column if not exists storage_fee numeric not null default 0;
alter table public.batches add column if not exists customs_duty numeric not null default 0;
alter table public.batches add column if not exists import_vat numeric not null default 0;
alter table public.batches add column if not exists clearance_fee numeric not null default 0;
alter table public.batches add column if not exists domestic_shipping numeric not null default 0;
alter table public.batches add column if not exists travel_cost numeric not null default 0;
alter table public.batches add column if not exists other_cost numeric not null default 0;

alter table public.products add column if not exists received_at timestamptz;
alter table public.products add column if not exists listed_at timestamptz;
alter table public.products add column if not exists sold_at timestamptz;

create table if not exists public.status_events (
  event_id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id text not null,
  from_status text,
  to_status text not null,
  note text,
  actor_email text,
  created_at timestamptz not null default now()
);
create index if not exists status_events_entity_idx on public.status_events(entity_type, entity_id, created_at desc);
alter table public.status_events enable row level security;
drop policy if exists auth_all_status_events on public.status_events;
create policy auth_all_status_events on public.status_events for all to authenticated using (true) with check (true);

create or replace function public.log_batch_status_event()
returns trigger language plpgsql security invoker set search_path=public as $$
begin
  if old.status is distinct from new.status then
    insert into public.status_events(entity_type,entity_id,from_status,to_status,actor_email)
    values('batch',new.batch_id,old.status,new.status,auth.jwt()->>'email');
  end if;
  return new;
end; $$;

create or replace function public.log_product_status_event()
returns trigger language plpgsql security invoker set search_path=public as $$
begin
  if old.inventory_status is distinct from new.inventory_status then
    insert into public.status_events(entity_type,entity_id,from_status,to_status,actor_email)
    values('product',new.product_id,old.inventory_status,new.inventory_status,auth.jwt()->>'email');
  end if;
  return new;
end; $$;

drop trigger if exists trg_batches_log_status on public.batches;
create trigger trg_batches_log_status after update of status on public.batches for each row execute function public.log_batch_status_event();
drop trigger if exists trg_products_log_status on public.products;
create trigger trg_products_log_status after update of inventory_status on public.products for each row execute function public.log_product_status_event();

create or replace function public.batch_status_before_update()
returns trigger language plpgsql security invoker set search_path=public as $$
begin
  if old.status is distinct from new.status then
    new.status_updated_at := now();
    if new.status = '통관중' and new.customs_entered_at is null then new.customs_entered_at := now(); end if;
    if new.status = '통관완료' and new.customs_cleared_at is null then new.customs_cleared_at := now(); end if;
    if new.status = '입고완료' and new.received_at is null then new.received_at := now(); end if;
  end if;
  new.updated_at := now();
  return new;
end; $$;

drop trigger if exists trg_batches_status_before_update on public.batches;
create trigger trg_batches_status_before_update before update on public.batches for each row execute function public.batch_status_before_update();

create or replace function public.product_status_timestamps()
returns trigger language plpgsql security invoker set search_path=public as $$
begin
  if old.inventory_status is distinct from new.inventory_status then
    if new.inventory_status='입고완료' and new.received_at is null then new.received_at:=now(); end if;
    if new.inventory_status='판매중' and new.listed_at is null then new.listed_at:=now(); end if;
    if new.inventory_status='판매완료' and new.sold_at is null then new.sold_at:=now(); end if;
  end if;
  new.updated_at:=now();
  return new;
end; $$;
drop trigger if exists trg_products_status_timestamps on public.products;
create trigger trg_products_status_timestamps before update on public.products for each row execute function public.product_status_timestamps();

create or replace function public.sync_products_from_batch_status()
returns trigger language plpgsql security invoker set search_path=public as $$
declare mapped text;
begin
  if old.status is not distinct from new.status then return new; end if;
  mapped := case new.status
    when '매입완료' then '매입완료'
    when '국제배송중' then '국제배송중'
    when '한국도착' then '한국도착'
    when '통관중' then '통관중'
    when '통관완료' then '통관완료'
    when '국내배송중' then '국내배송중'
    when '입고완료' then '입고완료'
    when '보류' then '보류'
    else null end;
  if mapped is not null then
    update public.products
       set inventory_status=mapped,
           received_at=case when mapped='입고완료' then coalesce(received_at,now()) else received_at end,
           updated_at=now()
     where batch_id=new.batch_id and inventory_status not in ('판매완료','반품');
  end if;
  return new;
end; $$;
drop trigger if exists trg_batches_sync_products on public.batches;
create trigger trg_batches_sync_products after update of status on public.batches for each row execute function public.sync_products_from_batch_status();

create or replace function public.sync_product_after_sale()
returns trigger language plpgsql security invoker set search_path=public as $$
begin
  update public.products set inventory_status='판매완료', sold_price=new.gross_amount, sold_at=coalesce(sold_at,now()), updated_at=now() where product_id=new.product_id;
  update public.listings set status='판매종료', updated_at=now() where product_id=new.product_id and status='판매중';
  return new;
end; $$;
drop trigger if exists trg_sales_sync_product on public.sales;
create trigger trg_sales_sync_product after insert on public.sales for each row execute function public.sync_product_after_sale();

create or replace function public.sync_product_from_listings()
returns trigger language plpgsql security invoker set search_path=public as $$
declare pid text; active_count int; current_status text; recv timestamptz;
begin
  if tg_op='DELETE' then pid:=old.product_id; else pid:=new.product_id; end if;
  select count(*) into active_count from public.listings where product_id=pid and status='판매중';
  select inventory_status,received_at into current_status,recv from public.products where product_id=pid;
  if current_status is null or current_status='판매완료' then
    if tg_op='DELETE' then return old; else return new; end if;
  end if;
  if active_count>0 then
    update public.products set inventory_status='판매중',listed_at=coalesce(listed_at,now()),updated_at=now() where product_id=pid;
  elsif current_status='판매중' then
    update public.products set inventory_status=case when recv is not null then '입고완료' else '촬영대기' end,updated_at=now() where product_id=pid;
  end if;
  if tg_op='DELETE' then return old; else return new; end if;
end; $$;
drop trigger if exists trg_listings_sync_product_iud on public.listings;
create trigger trg_listings_sync_product_iud after insert or update or delete on public.listings for each row execute function public.sync_product_from_listings();

create or replace function public.recalc_batch_aggregate(p_batch_id text)
returns void language plpgsql security invoker set search_path=public as $$
begin
  if p_batch_id is null then return; end if;
  update public.batches b
     set product_count=(select count(*) from public.products p where p.batch_id=p_batch_id),
         verified_cost=coalesce((select sum(p.verified_cost) from public.products p where p.batch_id=p_batch_id),0),
         updated_at=now()
   where b.batch_id=p_batch_id;
end; $$;

create or replace function public.products_recalc_batch_trigger()
returns trigger language plpgsql security invoker set search_path=public as $$
begin
  if tg_op='INSERT' then
    perform public.recalc_batch_aggregate(new.batch_id); return new;
  elsif tg_op='DELETE' then
    perform public.recalc_batch_aggregate(old.batch_id); return old;
  else
    if old.batch_id is distinct from new.batch_id then perform public.recalc_batch_aggregate(old.batch_id); end if;
    perform public.recalc_batch_aggregate(new.batch_id); return new;
  end if;
end; $$;
drop trigger if exists trg_products_recalc_batch on public.products;
create trigger trg_products_recalc_batch after insert or update of batch_id,verified_cost or delete on public.products for each row execute function public.products_recalc_batch_trigger();
